apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ecosystem
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com//tu-repositorio.git' # Cambia por tu repositorio
    targetRevision: HEAD
    path: applications  # Directorio donde están los manifiestos
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
