# applications/consumer.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: consumer
        image: montoliur/kafka-basic-consumer:v1 #use your own image
        args:
        - "-b"
        - "kafkas:9092"
        - "-t"
        - "test"
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafkas:9092" #Kafka broker
        - name: TOPIC
          value: "test"       # Topic

