# producer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: montoliur/kafka-basic-producer:v1 # Cambia a tu imagen del producer
        args:
        - "-b"
        - "kafka:9092"
        - "-t"
        - "test"
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka:9092" # Dirección del broker Kafka
        - name: TOPIC
          value: "test"       # Topic al que producirá mensajes
        restartPolicy: Always