
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: <your-image>/kafka-basic-producer:v1 # Cambia a tu imagen del producer
        args:
        - "-b"
        - "kafkas:9092"
        - "-t"
        - "test"
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafkas:9092" # Kafkas broker
        - name: TOPIC
          value: "test"       # Topic 
